#pragma region RU_23_11_19_RU
enum I64_ADDRESSES_RU : __int64
{
	I_SSYSTEMGLOBALENVIRONMENT_ADR = 0x141C02CD0,
	I_IGAMEF_RAMEWORK_ADR = 0x141D79D80,
	I_IS_SAME_TEAM_FA = 0x140FCB5F0,
	I_DIRECT_DEVICE_ADR = 0x141ECF9F8

};//enum I64_ADDRESSES_RU : __int64

enum I_OFFSETS_VAR_RU : int
{
	SSG_ENTITY_SYSTEM = 0xD8,

	A_GET_ID = 0x20,
	A_GET_PLAYER = 0xD10,

	P_IGNORE_RECOIL = 0xB1,

	
	IDD_GET_CLIENT_DEVICE = 0xA6E0,
	I_ENDSCENE_OFFSET = 0x2A,
};//enum I_OFFSETS_RU : int

enum I_OFFSETS_FUNK_RU : int
{
	F_GET_CLIENTACTOR = 0x470,
	F_GET_GAMERULES = 0x448,
	F_GET_IACTORSYSTEM = 0xC8,

	A_ISDEAD = 0xC0,
	
	AS_GET_ACTOR = 0x78,

	IES_GET_ENTITY_ITERATOR = 0xA0,

	IEI_GET_NEXT = 0x30,

	IE_GET_PROXY = 0x1D8,
	IE_GET_ID = 0x8,

	IRP_RENDER_PROXY_SETHUD = 0x160,
	IRP_GET_RENDERNODE = 0xA0,


};//enum I_OFFSETS_FUNK_RU : int

#pragma endregion

#pragma region EU_23_11_19_EU

enum I64_ADDRESSES_EU : __int64
{
	I_SSYSTEMGLOBALENVIRONMENT_ADR_EU = 0x141C03D30,//+
	I_IGAMEF_RAMEWORK_ADR_EU = 0x141D7ADE0,//+
	I_IS_SAME_TEAM_FA_EU = 0x140FCB890,//+
	I_DIRECT_DEVICE_ADR_EU = 0x141ED0A58//+

};//enum I64_ADDRESSES_EU : __int64

enum I_OFFSETS_VAR_EU : int
{
	SSG_ENTITY_SYSTEM_EU = 0xD8, //+

	A_GET_ID_EU = 0x20,//+
	A_GET_PLAYER_EU = 0xD10,//+

	P_IGNORE_RECOIL_EU = 0xB1,//+


	IDD_GET_CLIENT_DEVICE_EU = 0xA6E0,//+
	I_ENDSCENE_OFFSET_EU = 0x2A,//+
};//enum I_OFFSETS_EU : int

enum I_OFFSETS_FUNK_EU : int
{
	F_GET_CLIENTACTOR_EU = 0x470,//+
	F_GET_GAMERULES_EU = 0x448,//+
	F_GET_IACTORSYSTEM_EU = 0xC8,//+

	A_ISDEAD_EU = 0xC0,//+

	AS_GET_ACTOR_EU = 0x78,//+

	IES_GET_ENTITY_ITERATOR_EU = 0xA0,//+

	IEI_GET_NEXT_EU = 0x30,//+

	IE_GET_PROXY_EU = 0x1D8,//+
	IE_GET_ID_EU = 0x8,//+

	IRP_RENDER_PROXY_SETHUD_EU = 0x160,//+
	IRP_GET_RENDERNODE_EU = 0xA0,//+


};//enum I_OFFSETS_FUNK_EU : int

#pragma endregion
